'use strict';
const APP_VERSION='3.0.0';
const STORAGE={settings:'rk_tp_v3_settings',draft:'rk_tp_v3_draft',library:'rk_tp_v3_library',keys:'rk_tp_v3_keys',gamepad:'rk_tp_v3_gamepad'};
const $=id=>document.getElementById(id);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const formatTime=(seconds)=>{if(!Number.isFinite(seconds)||seconds<0)return'--:--';seconds=Math.floor(seconds);const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
const safeJson=(s,fallback)=>{try{return JSON.parse(s)}catch{return fallback}};
const downloadFile=(name,data,type='text/plain;charset=utf-8')=>{const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)};
const slug=s=>(s||'script').trim().replace(/[^a-zA-Z0-9\u0C00-\u0C7F\u0900-\u097F]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60)||'script';

const state={playing:false,scrollY:0,lastTs:0,raf:0,speedPx:55,events:[],marks:[],fired:new Set(),maxY:0,guideY:0,wordCount:0,voice:null,voiceOn:false,wakeLock:null,timerStart:0,pauseStarted:0,totalPaused:0,midPauseTimer:null,countdownActive:false,pointerStart:null,gamepadPrev:[],gamepadAxisLatch:{x:0,y:0},learningKeyAction:null,learningGamepadAction:null,hideTimer:null};
const defaults={fontSize:58,lineHeight:1.48,textWidth:82,guidePos:43,fontWeight:600,dimLevel:0,textAlign:'center',textColor:'#ffffff',bgColor:'#000000',mirrorX:true,flipY:false,guide:true,hud:true,paceMode:'wpm',paceValue:135,paceStep:5,jumpSeconds:2,startCountdown:3,voiceLang:'en-IN',orientation:'auto',touchGestures:true,wakeLock:true,production:'RK Video',scene:'1',take:1};
let settings={...defaults};
const actions={playPause:'Play / Pause',faster:'Faster',slower:'Slower',nudgeBack:'Nudge Back',nudgeForward:'Nudge Forward',prevMark:'Previous Mark',nextMark:'Next Mark',fontUp:'Font Bigger',fontDown:'Font Smaller',toggleMirror:'Toggle Mirror',toggleGuide:'Toggle Guide',toggleHud:'Toggle HUD',restart:'Restart',goStart:'Go to Start',goEnd:'Go to End',takePlus:'Take +1',toggleSlate:'Toggle Slate',exit:'Exit Prompt'};
const defaultKeys={
  Space:'playPause',ArrowUp:'faster',ArrowDown:'slower',ArrowLeft:'nudgeBack',ArrowRight:'nudgeForward',PageUp:'prevMark',PageDown:'nextMark',Equal:'fontUp',NumpadAdd:'fontUp',Minus:'fontDown',NumpadSubtract:'fontDown',KeyM:'toggleMirror',KeyG:'toggleGuide',KeyH:'toggleHud',KeyR:'restart',Home:'goStart',End:'goEnd',KeyN:'takePlus',Escape:'exit',MediaPlayPause:'playPause',MediaTrackPrevious:'prevMark',MediaTrackNext:'nextMark'};
let keyMap={...defaultKeys},gamepadMap={};

function getScriptText(){return $('scriptInput').value}
function scriptStats(){const raw=getScriptText(),clean=raw.replace(/<<[^>]*>>/g,' ').replace(/\s+/g,' ').trim(),words=clean?clean.split(/\s+/).length:0,marks=(raw.match(/<<mark(?::[^>]*)?>>/gi)||[]).length;$('wordCount').textContent=words;$('charCount').textContent=raw.length;$('markCount').textContent=marks;const wpm=settings.paceMode==='wpm'?settings.paceValue:135;$('estimatedTime').textContent=formatTime(words/(wpm/60));return{words,marks}}
function saveDraft(){const payload={title:$('scriptTitle').value,text:getScriptText(),updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE.draft,JSON.stringify(payload));$('draftStatus').textContent='Auto-saved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('autosaveBadge').textContent='Auto-saved';}
let autoSaveTimer;function scheduleSave(){clearTimeout(autoSaveTimer);autoSaveTimer=setTimeout(saveDraft,650);scriptStats()}
function loadDraft(){const d=safeJson(localStorage.getItem(STORAGE.draft),null);if(d){$('scriptTitle').value=d.title||'';$('scriptInput').value=d.text||'';$('draftStatus').textContent='Recovered '+(d.updatedAt?new Date(d.updatedAt).toLocaleString():'locally')}else{$('scriptTitle').value='RK Teleprompter Demo';$('scriptInput').value=`<<wpm:135>><<mark:INTRO>>Hello! This is RK Teleprompter Pro V3.\n\nThe text begins at the reading line, helping you maintain a natural eye-line.\n\n<<cue:SMILE>>Use a relaxed expression and speak conversationally.\n\n<<pause:2>>This is a two-second automatic pause.\n\n<<mark:MAIN POINT>>You can jump between named sections from the remote, keyboard, mouse, touchscreen, or gamepad.\n\n<<wpm:120>>This section deliberately slows down.\n\n<<pause>>This is a manual pause. Press Play to continue.\n\n<<mark:ENDING>><<cue:LOOK AT CAMERA>>Thank the audience and finish clearly.`}scriptStats()}

function saveSettings(){localStorage.setItem(STORAGE.settings,JSON.stringify(settings))}
function loadSettings(){settings={...defaults,...safeJson(localStorage.getItem(STORAGE.settings),{})};keyMap={...defaultKeys,...safeJson(localStorage.getItem(STORAGE.keys),{})};gamepadMap=safeJson(localStorage.getItem(STORAGE.gamepad),{})||{}}
function syncControls(){const pairs={fontSize:'fontSize',lineHeight:'lineHeight',textWidth:'textWidth',guidePos:'guidePos',fontWeight:'fontWeight',dimLevel:'dimLevel',textAlign:'textAlign',textColor:'textColor',bgColor:'bgColor',paceMode:'paceMode',paceValue:'paceValue',paceStep:'paceStep',jumpSeconds:'jumpSeconds',startCountdown:'startCountdown',voiceLang:'voiceLang',production:'production',scene:'scene',take:'take'};for(const[id,key]of Object.entries(pairs))$(id).value=settings[key];$('mirrorBtn').classList.toggle('active',settings.mirrorX);$('mirrorBtn').textContent=`Mirror X: ${settings.mirrorX?'ON':'OFF'}`;$('flipYBtn').classList.toggle('active',settings.flipY);$('flipYBtn').textContent=`Flip Y: ${settings.flipY?'ON':'OFF'}`;$('guideBtn').classList.toggle('active',settings.guide);$('guideBtn').textContent=`Guide: ${settings.guide?'ON':'OFF'}`;$('hudBtn').classList.toggle('active',settings.hud);$('hudBtn').textContent=`HUD: ${settings.hud?'ON':'OFF'}`;$('touchGestureBtn').classList.toggle('active',settings.touchGestures);$('touchGestureBtn').textContent=`Touch gestures: ${settings.touchGestures?'ON':'OFF'}`;$('wakeLockBtn').classList.toggle('active',settings.wakeLock);$('wakeLockBtn').textContent=`Keep screen awake: ${settings.wakeLock?'ON':'OFF'}`;$('orientationBtn').textContent=`Landscape lock: ${settings.orientation==='landscape'?'ON':'AUTO'}`;updateOutputs();applyPromptAppearance()}
function updateOutputs(){$('fontSizeOut').textContent=settings.fontSize+' px';$('lineHeightOut').textContent=Number(settings.lineHeight).toFixed(2);$('textWidthOut').textContent=settings.textWidth+'%';$('guidePosOut').textContent=settings.guidePos+'%';$('fontWeightOut').textContent=settings.fontWeight;$('dimOut').textContent=settings.dimLevel+'%';$('paceLabel').firstChild.textContent=settings.paceMode==='wpm'?'Target WPM ':'Pixels per second ';$('paceOut').textContent=settings.paceValue;$('paceStepOut').textContent=settings.paceStep;$('jumpSecondsOut').textContent=Number(settings.jumpSeconds).toFixed(1)+' sec';$('countdownOut').textContent=settings.startCountdown+' sec';scriptStats()}
function applyPromptAppearance(){document.documentElement.style.setProperty('--prompt-size',settings.fontSize+'px');document.documentElement.style.setProperty('--prompt-lh',settings.lineHeight);document.documentElement.style.setProperty('--prompt-width',settings.textWidth+'%');document.documentElement.style.setProperty('--prompt-weight',settings.fontWeight);document.documentElement.style.setProperty('--prompt-align',settings.textAlign);document.documentElement.style.setProperty('--guide-pos',settings.guidePos+'%');document.documentElement.style.setProperty('--dim-opacity',settings.dimLevel/100);document.documentElement.style.setProperty('--prompt-text',settings.textColor);document.documentElement.style.setProperty('--prompt-bg',settings.bgColor);$('promptScreen').classList.toggle('mirror-x',settings.mirrorX);$('promptScreen').classList.toggle('flip-y',settings.flipY);$('promptScreen').classList.toggle('guide-hidden',!settings.guide);$('promptScreen').classList.toggle('hud-hidden',!settings.hud);$('slateText').textContent=`${settings.production||'RK'} · S${settings.scene||'—'} · T${settings.take||1}`}

function library(){return safeJson(localStorage.getItem(STORAGE.library),[])||[]}
function setLibrary(items){localStorage.setItem(STORAGE.library,JSON.stringify(items));renderLibrary()}
function saveToLibrary(){const title=$('scriptTitle').value.trim()||'Untitled Script',items=library(),entry={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),title,text:getScriptText(),settings:{...settings},updatedAt:new Date().toISOString()};const existing=items.findIndex(x=>x.title.toLowerCase()===title.toLowerCase());if(existing>=0){entry.id=items[existing].id;items[existing]=entry}else items.unshift(entry);setLibrary(items);toastSetup('Saved to library')}
function renderLibrary(){const box=$('libraryList'),items=library();box.innerHTML='';if(!items.length){box.innerHTML='<div class="library-item"><div><strong>No saved scripts yet</strong><small>Use “Save to Library”.</small></div></div>';return}items.forEach(item=>{const row=document.createElement('div');row.className='library-item';const meta=document.createElement('div');meta.innerHTML=`<strong></strong><small>${new Date(item.updatedAt).toLocaleString()} · ${(item.text||'').replace(/<<[^>]*>>/g,' ').trim().split(/\s+/).filter(Boolean).length} words</small>`;meta.querySelector('strong').textContent=item.title;const buttons=document.createElement('div');const load=document.createElement('button');load.className='btn small';load.textContent='Load';load.onclick=()=>{if(!confirm('Load this script and replace the current draft?'))return;$('scriptTitle').value=item.title;$('scriptInput').value=item.text||'';if(item.settings)settings={...settings,...item.settings};syncControls();saveDraft();toastSetup('Script loaded')};const del=document.createElement('button');del.className='btn small danger';del.textContent='Delete';del.onclick=()=>{if(confirm('Delete this saved script?'))setLibrary(items.filter(x=>x.id!==item.id))};buttons.append(load,del);row.append(meta,buttons);box.append(row)})}
function newScript(){if(getScriptText().trim()&&!confirm('Start a new script? The current draft is auto-saved, but save it to the Library for a named copy.'))return;$('scriptTitle').value='';$('scriptInput').value='';saveDraft();scriptStats();$('scriptInput').focus()}

function exportCurrentJson(){const payload={app:'RK Teleprompter Pro',version:APP_VERSION,exportedAt:new Date().toISOString(),title:$('scriptTitle').value,text:getScriptText(),settings:{...settings}};downloadFile(slug(payload.title)+'_RK_Teleprompter.json',JSON.stringify(payload,null,2),'application/json;charset=utf-8')}
function exportAll(){const payload={app:'RK Teleprompter Pro',version:APP_VERSION,exportedAt:new Date().toISOString(),library:library(),draft:safeJson(localStorage.getItem(STORAGE.draft),null),settings,keyMap,gamepadMap};downloadFile('RK_Teleprompter_Full_Backup.json',JSON.stringify(payload,null,2),'application/json;charset=utf-8')}
async function importFile(file){const text=await file.text();if(file.name.toLowerCase().endsWith('.json')){const data=safeJson(text,null);if(!data)throw new Error('Invalid JSON');if(Array.isArray(data.library)){if(confirm('This is a full backup. Import its script library and settings?')){setLibrary(data.library);if(data.settings){settings={...defaults,...data.settings};saveSettings()}if(data.keyMap){keyMap={...defaultKeys,...data.keyMap};localStorage.setItem(STORAGE.keys,JSON.stringify(keyMap))}if(data.gamepadMap){gamepadMap=data.gamepadMap;localStorage.setItem(STORAGE.gamepad,JSON.stringify(gamepadMap))}if(data.draft){$('scriptTitle').value=data.draft.title||'';$('scriptInput').value=data.draft.text||''}syncControls();renderKeyMappings();renderGamepadMappings();saveDraft()}}else if(typeof data.text==='string'||typeof data.script==='string'){$('scriptTitle').value=data.title||file.name.replace(/\.[^.]+$/,'');$('scriptInput').value=data.text??data.script;if(data.settings){settings={...settings,...data.settings};syncControls();saveSettings()}saveDraft()}else throw new Error('No script found in JSON')}else{$('scriptTitle').value=file.name.replace(/\.[^.]+$/,'');$('scriptInput').value=text;saveDraft()}scriptStats();toastSetup('Import completed')}

function escapeHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function parseScript(raw){let seq=0;const clean=escapeHtml(raw);const markerRe=/&lt;&lt;([a-zA-Z]+)(?::(.*?))?&gt;&gt;/g;const replaced=clean.replace(markerRe,(full,type,val='')=>{type=type.toLowerCase();val=val.trim();if(!['mark','pause','speed','wpm','cue','countdown'].includes(type))return full;const id='evt_'+seq++;return `<span class="event-marker" data-event-id="${id}" data-event-type="${type}" data-event-value="${encodeURIComponent(val)}"></span>`});const paras=replaced.split(/\n{2,}/).map(p=>`<p>${p.replace(/\n/g,'<br>')}</p>`).join('');return paras||'<p></p>'}
function preparePrompt(){const raw=getScriptText();$('promptContent').innerHTML=parseScript(raw);state.wordCount=scriptStats().words;applyPromptAppearance();requestAnimationFrame(()=>{computeGeometry();collectEvents();state.scrollY=0;state.fired.clear();updateTransform();updateHud()})}
function computeGeometry(){const vh=$('promptViewport').clientHeight;state.guideY=vh*(settings.guidePos/100);$('promptContent').style.paddingTop=state.guideY+'px';$('promptContent').style.paddingBottom=(vh-state.guideY+settings.fontSize*1.7)+'px';state.maxY=Math.max(0,$('promptTrack').scrollHeight-vh);calculateSpeed()}
function collectEvents(){state.events=[...$('promptContent').querySelectorAll('.event-marker')].map(el=>({id:el.dataset.eventId,type:el.dataset.eventType,value:decodeURIComponent(el.dataset.eventValue||''),top:el.offsetTop})).sort((a,b)=>a.top-b.top);state.marks=state.events.filter(e=>e.type==='mark').map(e=>({...e,name:e.value||'Mark'}))}
function calculateSpeed(){if(settings.paceMode==='px'){state.speedPx=Number(settings.paceValue);return}const durationSec=Math.max(1,state.wordCount/(Number(settings.paceValue)/60));state.speedPx=state.maxY/durationSec;if(!Number.isFinite(state.speedPx)||state.speedPx<1)state.speedPx=28}
function updateTransform(){let sx=settings.mirrorX?-1:1,sy=settings.flipY?-1:1;$('promptTrack').style.transform=`translate3d(0,${-state.scrollY}px,0) scale(${sx},${sy})`}
function currentReadY(){return state.scrollY+state.guideY}
function processEvents(){const readY=currentReadY();for(const e of state.events){if(state.fired.has(e.id)||e.top>readY+5)continue;state.fired.add(e.id);handleMarker(e)}}
function handleMarker(e){switch(e.type){case'mark':$('hudMark').textContent=e.value||'Mark';showCue(e.value||'MARK',800);break;case'cue':showCue(e.value||'CUE',1800);break;case'speed':settings.paceMode='px';settings.paceValue=clamp(Number(e.value)||60,1,400);syncControls();calculateSpeed();showCue(`Speed ${settings.paceValue} px/s`,1100);break;case'wpm':settings.paceMode='wpm';settings.paceValue=clamp(Number(e.value)||135,40,300);syncControls();calculateSpeed();showCue(`${settings.paceValue} WPM`,1100);break;case'pause':if(e.value){timedPause(clamp(Number(e.value)||1,.2,60))}else{setPlaying(false);showCue('PAUSED',1200)}break;case'countdown':midCountdown(clamp(parseInt(e.value)||3,1,10));break}}
function showCue(text,ms=1400){const el=$('cueToast');el.textContent=text;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),ms)}
function timedPause(seconds){const resume=state.playing;setPlaying(false);showCue(`PAUSE ${seconds}s`,Math.min(seconds*1000,2500));clearTimeout(state.midPauseTimer);state.midPauseTimer=setTimeout(()=>{if(resume)setPlaying(true)},seconds*1000)}
async function midCountdown(seconds){if(state.countdownActive)return;state.countdownActive=true;const resume=state.playing;setPlaying(false);await runCountdown(seconds);state.countdownActive=false;if(resume)setPlaying(true)}
function updateHud(){const p=state.maxY?clamp(state.scrollY/state.maxY,0,1):0;$('progressFill').style.width=(p*100).toFixed(1)+'%';$('hudProgress').textContent=Math.round(p*100)+'%';$('hudPace').textContent=settings.paceMode==='wpm'?`${settings.paceValue} WPM`:`${Math.round(state.speedPx)} px/s`;$('hudRemaining').textContent=state.speedPx>0?formatTime((state.maxY-state.scrollY)/state.speedPx):'--:--';$('playState').textContent=state.playing?'RUNNING':'PAUSED';$('dockPlay').textContent=state.playing?'Ⅱ Pause':'▶ Play';const elapsed=state.timerStart?(performance.now()-state.timerStart)/1000:0;$('elapsed').textContent=formatTime(elapsed)}
function animationLoop(ts){if(!state.lastTs)state.lastTs=ts;const dt=Math.min(.06,(ts-state.lastTs)/1000);state.lastTs=ts;if(state.playing&&!state.countdownActive){state.scrollY=clamp(state.scrollY+state.speedPx*dt,0,state.maxY);if(state.scrollY>=state.maxY)setPlaying(false);updateTransform();processEvents()}updateHud();state.raf=requestAnimationFrame(animationLoop)}
function setPlaying(on){state.playing=!!on;if(on){state.pauseStarted=0;state.lastTs=performance.now()}scheduleHudHide()}
function changePace(dir){const step=Number(settings.paceStep);settings.paceValue=clamp(Number(settings.paceValue)+dir*step,settings.paceMode==='wpm'?40:1,settings.paceMode==='wpm'?300:400);$('paceValue').value=settings.paceValue;updateOutputs();calculateSpeed();saveSettings();showCue(dir>0?'FASTER':'SLOWER',650)}
function nudge(dir){state.scrollY=clamp(state.scrollY+dir*state.speedPx*Number(settings.jumpSeconds),0,state.maxY);state.fired=new Set(state.events.filter(e=>e.top<currentReadY()-8).map(e=>e.id));updateTransform();updateHud();scheduleHudHide()}
function jumpMark(dir){const y=currentReadY();let target;if(dir>0)target=state.marks.find(m=>m.top>y+12);else{const arr=state.marks.filter(m=>m.top<y-12);target=arr[arr.length-1]}if(target){state.scrollY=clamp(target.top-state.guideY,0,state.maxY);state.fired=new Set(state.events.filter(e=>e.top<currentReadY()-8).map(e=>e.id));$('hudMark').textContent=target.name;updateTransform();showCue(target.name,850)}else showCue(dir>0?'NO NEXT MARK':'NO PREVIOUS MARK',850)}
function perform(action){$('inputBadge').textContent='Remote: '+(actions[action]||action);switch(action){case'playPause':setPlaying(!state.playing);break;case'faster':changePace(1);break;case'slower':changePace(-1);break;case'nudgeBack':nudge(-1);break;case'nudgeForward':nudge(1);break;case'prevMark':jumpMark(-1);break;case'nextMark':jumpMark(1);break;case'fontUp':settings.fontSize=clamp(settings.fontSize+4,26,180);syncControls();computeGeometry();break;case'fontDown':settings.fontSize=clamp(settings.fontSize-4,26,180);syncControls();computeGeometry();break;case'toggleMirror':settings.mirrorX=!settings.mirrorX;syncControls();updateTransform();break;case'toggleGuide':settings.guide=!settings.guide;syncControls();break;case'toggleHud':settings.hud=!settings.hud;syncControls();break;case'restart':state.scrollY=0;state.fired.clear();updateTransform();break;case'goStart':state.scrollY=0;state.fired.clear();updateTransform();break;case'goEnd':state.scrollY=state.maxY;updateTransform();break;case'takePlus':settings.take=Number(settings.take||1)+1;$('take').value=settings.take;applyPromptAppearance();saveSettings();showCue('TAKE '+settings.take,800);break;case'toggleSlate':$('slateBox').classList.toggle('hidden');break;case'exit':exitPrompt();break}scheduleHudHide()}
function scheduleHudHide(){clearTimeout(state.hideTimer);if(!settings.hud)return;$('promptScreen').classList.remove('hud-hidden');state.hideTimer=setTimeout(()=>{if(state.playing)$('promptScreen').classList.add('hud-hidden')},4500)}

async function requestWakeLock(){if(!settings.wakeLock)return;try{if('wakeLock'in navigator){state.wakeLock=await navigator.wakeLock.request('screen');$('wakeBadge').textContent='Wake lock: active';$('wakeBadge').classList.add('ok')}else $('wakeBadge').textContent='Wake lock: unsupported'}catch(e){$('wakeBadge').textContent='Wake lock: blocked'}}
async function releaseWakeLock(){try{await state.wakeLock?.release()}catch{}state.wakeLock=null;$('wakeBadge').textContent='Wake lock: standby'}
async function applyOrientation(){if(settings.orientation==='landscape'&&screen.orientation?.lock){try{await screen.orientation.lock('landscape')}catch{}}}
async function startPrompt(){saveDraft();preparePrompt();$('setupApp').classList.add('hidden');$('promptScreen').classList.remove('hidden');state.timerStart=performance.now();state.lastTs=performance.now();try{await document.documentElement.requestFullscreen?.()}catch{}await applyOrientation();await requestWakeLock();clearCancelTimers();const c=Number(settings.startCountdown);if(c>0)await runCountdown(c);setPlaying(true);cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(animationLoop);scheduleHudHide()}
function clearCancelTimers(){clearTimeout(state.midPauseTimer);state.midPauseTimer=null}
async function runCountdown(n){const el=$('countdownOverlay');el.classList.remove('hidden');for(let i=n;i>=1;i--){el.textContent=i;await new Promise(r=>setTimeout(r,1000))}el.textContent='GO';await new Promise(r=>setTimeout(r,350));el.classList.add('hidden')}
async function exitPrompt(){setPlaying(false);clearCancelTimers();cancelAnimationFrame(state.raf);state.raf=0;$('promptScreen').classList.add('hidden');$('setupApp').classList.remove('hidden');await releaseWakeLock();try{screen.orientation?.unlock?.()}catch{}try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}stopVoice();saveSettings();window.scrollTo(0,0)}

function renderKeyMappings(){const body=$('keyMappingBody');body.innerHTML='';const primaryActions=['playPause','faster','slower','nudgeBack','nudgeForward','prevMark','nextMark','fontUp','fontDown','toggleMirror','toggleGuide','toggleHud','restart','takePlus','exit'];for(const action of primaryActions){const codes=Object.entries(keyMap).filter(([,a])=>a===action).map(([c])=>c);const tr=document.createElement('tr');const td1=document.createElement('td');td1.textContent=actions[action];const td2=document.createElement('td');td2.innerHTML=codes.length?codes.map(c=>`<span class="keycap">${c}</span>`).join(' '):'<span class="subtle">Unassigned</span>';const td3=document.createElement('td');const b=document.createElement('button');b.className='btn small';b.textContent='Learn';b.onclick=()=>{state.learningKeyAction=action;b.textContent='Press key…';toastSetup('Press the desired keyboard or remote key')};td3.append(b);tr.append(td1,td2,td3);body.append(tr)}}
function handleKey(e){$('lastKey').textContent=`${e.code} (${e.key})`;$('inputBadge').textContent='Remote: '+e.code;if(state.learningKeyAction){e.preventDefault();for(const[c,a]of Object.entries(keyMap))if(a===state.learningKeyAction&&c===e.code)delete keyMap[c];keyMap[e.code]=state.learningKeyAction;localStorage.setItem(STORAGE.keys,JSON.stringify(keyMap));state.learningKeyAction=null;renderKeyMappings();toastSetup('Key mapped');return}if(!$('promptScreen').classList.contains('hidden')){const action=keyMap[e.code]||keyMap[e.key];if(action){e.preventDefault();perform(action)}}}

function renderGamepadActions(){const sel=$('gamepadAction');sel.innerHTML='';for(const[k,v]of Object.entries(actions)){const o=document.createElement('option');o.value=k;o.textContent=v;sel.append(o)}renderGamepadMappings()}
function renderGamepadMappings(){const entries=Object.entries(gamepadMap);$('gamepadMappings').innerHTML=entries.length?entries.map(([b,a])=>`<span class="keycap">Button ${b}</span> → ${actions[a]||a}`).join('<br>'):'No custom gamepad mappings.'}
function pollGamepads(){const gps=navigator.getGamepads?.()||[],gp=[...gps].find(Boolean);if(!gp){$('gamepadName').textContent='Not detected';requestAnimationFrame(pollGamepads);return}$('gamepadName').textContent=gp.id.slice(0,50);const axes=gp.axes.map(v=>Math.abs(v)<.08?0:v);$('axisReadout').textContent=axes.map(v=>v.toFixed(2)).join(', ');gp.buttons.forEach((b,i)=>{const prev=state.gamepadPrev[i]||false;if(b.pressed&&!prev){$('lastGamepadButton').textContent='Button '+i;$('inputBadge').textContent='Remote: Gamepad B'+i;if(state.learningGamepadAction){gamepadMap[i]=state.learningGamepadAction;state.learningGamepadAction=null;localStorage.setItem(STORAGE.gamepad,JSON.stringify(gamepadMap));renderGamepadMappings();showCue('GAMEPAD MAPPED',800)}else if(!$('promptScreen').classList.contains('hidden')){const action=gamepadMap[i]||({0:'playPause',4:'slower',5:'faster',12:'faster',13:'slower',14:'nudgeBack',15:'nudgeForward'}[i]);if(action)perform(action)}}state.gamepadPrev[i]=b.pressed});if(!$('promptScreen').classList.contains('hidden')){const x=axes[0]||0,y=axes[1]||0;if(Math.abs(x)>.72&&state.gamepadAxisLatch.x===0){nudge(Math.sign(x));state.gamepadAxisLatch.x=Math.sign(x)}else if(Math.abs(x)<.3)state.gamepadAxisLatch.x=0;if(Math.abs(y)>.72&&state.gamepadAxisLatch.y===0){changePace(-Math.sign(y));state.gamepadAxisLatch.y=Math.sign(y)}else if(Math.abs(y)<.3)state.gamepadAxisLatch.y=0}requestAnimationFrame(pollGamepads)}

function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toastSetup('Speech recognition is unavailable in this browser');return}if(state.voiceOn){stopVoice();return}const r=new SR();r.continuous=true;r.interimResults=false;r.lang=settings.voiceLang;r.onresult=ev=>{for(let i=ev.resultIndex;i<ev.results.length;i++)handleVoice(ev.results[i][0].transcript.toLowerCase())};r.onerror=e=>toastSetup('Voice error: '+e.error);r.onend=()=>{state.voiceOn=false;$('voiceBtn').textContent='🎙 Start voice control'};try{r.start();state.voice=r;state.voiceOn=true;$('voiceBtn').textContent='■ Stop voice control';toastSetup('Voice control started')}catch(e){toastSetup('Could not start voice control')}}
function stopVoice(){try{state.voice?.stop()}catch{}state.voice=null;state.voiceOn=false;$('voiceBtn').textContent='🎙 Start voice control'}
function handleVoice(t){const has=(...xs)=>xs.some(x=>t.includes(x));if(has('pause','stop','ఆపు','ఆపండి','रुको','रुक')){if(state.playing)perform('playPause')}else if(has('resume','continue','play','కొనసాగించు','మొదలు','चलो','शुरू')){if(!state.playing)perform('playPause')}else if(has('faster','speed up','వేగం పెంచు','तेज़','तेज'))perform('faster');else if(has('slower','slow down','వేగం తగ్గించు','धीमा'))perform('slower');else if(has('next mark','next section','తర్వాతి భాగం','अगला'))perform('nextMark');else if(has('previous mark','previous section','ముందరి భాగం','पिछला'))perform('prevMark');else if(has('mirror','మిర్రర్'))perform('toggleMirror');else if(has('hide controls','hide hud','కంట్రోల్స్ దాచు'))perform('toggleHud')}

function toastSetup(text){$('draftStatus').textContent=text;clearTimeout($('draftStatus')._t);$('draftStatus')._t=setTimeout(()=>$('draftStatus').textContent='Ready',2200)}
function insertAtCursor(text){const ta=$('scriptInput'),s=ta.selectionStart,e=ta.selectionEnd;ta.setRangeText(text,s,e,'end');ta.focus();scheduleSave()}
function setupBindings(){
  $('scriptInput').addEventListener('input',scheduleSave);$('scriptTitle').addEventListener('input',scheduleSave);$('newScriptBtn').onclick=newScript;$('saveLibraryBtn').onclick=saveToLibrary;$('startBtn').onclick=startPrompt;
  document.querySelectorAll('[data-insert]').forEach(b=>b.onclick=()=>insertAtCursor(b.dataset.insert));$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const f=e.target.files[0];if(f)try{await importFile(f)}catch(err){alert('Import failed: '+err.message)}e.target.value=''};$('exportTxtBtn').onclick=()=>downloadFile(slug($('scriptTitle').value)+'.txt',getScriptText());$('exportJsonBtn').onclick=exportCurrentJson;$('exportAllBtn').onclick=exportAll;$('clearLibraryBtn').onclick=()=>{if(confirm('Delete every saved library script on this device?'))setLibrary([])};
  const numeric=['fontSize','lineHeight','textWidth','guidePos','fontWeight','dimLevel','paceValue','paceStep','jumpSeconds','startCountdown','take'];numeric.forEach(id=>$(id).addEventListener('input',()=>{settings[id]=Number($(id).value);updateOutputs();applyPromptAppearance();saveSettings()}));['textAlign','textColor','bgColor','paceMode','voiceLang','production','scene'].forEach(id=>$(id).addEventListener('input',()=>{settings[id]=$(id).value;if(id==='paceMode'){const wpm=settings.paceMode==='wpm';$('paceValue').min=wpm?40:1;$('paceValue').max=wpm?300:400;if(wpm&&settings.paceValue>300)settings.paceValue=135;$('paceValue').value=settings.paceValue}updateOutputs();applyPromptAppearance();saveSettings()}));
  $('mirrorBtn').onclick=()=>{settings.mirrorX=!settings.mirrorX;syncControls();saveSettings()};$('flipYBtn').onclick=()=>{settings.flipY=!settings.flipY;syncControls();saveSettings()};$('guideBtn').onclick=()=>{settings.guide=!settings.guide;syncControls();saveSettings()};$('hudBtn').onclick=()=>{settings.hud=!settings.hud;syncControls();saveSettings()};$('touchGestureBtn').onclick=()=>{settings.touchGestures=!settings.touchGestures;syncControls();saveSettings()};$('wakeLockBtn').onclick=()=>{settings.wakeLock=!settings.wakeLock;syncControls();saveSettings()};$('orientationBtn').onclick=()=>{settings.orientation=settings.orientation==='landscape'?'auto':'landscape';syncControls();saveSettings()};$('resetDisplayBtn').onclick=()=>{Object.assign(settings,{fontSize:58,lineHeight:1.48,textWidth:82,guidePos:43,fontWeight:600,dimLevel:0,textAlign:'center',textColor:'#ffffff',bgColor:'#000000',mirrorX:true,flipY:false,guide:true,hud:true});syncControls();saveSettings()};$('voiceBtn').onclick=startVoice;
  $('exitBtn').onclick=exitPrompt;document.querySelectorAll('#controlDock [data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();perform(b.dataset.action)});
  $('resetKeysBtn').onclick=()=>{keyMap={...defaultKeys};localStorage.setItem(STORAGE.keys,JSON.stringify(keyMap));renderKeyMappings()};$('learnGamepadBtn').onclick=()=>{state.learningGamepadAction=$('gamepadAction').value;toastSetup('Press the gamepad button now')};$('resetGamepadBtn').onclick=()=>{gamepadMap={};localStorage.setItem(STORAGE.gamepad,'{}');renderGamepadMappings()};
  window.addEventListener('keydown',handleKey,{capture:true});window.addEventListener('resize',()=>{if(!$('promptScreen').classList.contains('hidden')){computeGeometry();collectEvents();state.scrollY=clamp(state.scrollY,0,state.maxY);updateTransform()}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!$('promptScreen').classList.contains('hidden'))requestWakeLock()});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&!$('promptScreen').classList.contains('hidden'))showCue('FULLSCREEN EXITED',900)});
  const ps=$('promptScreen');ps.addEventListener('pointerdown',e=>{if(!settings.touchGestures||e.target.closest('button'))return;state.pointerStart={x:e.clientX,y:e.clientY,t:performance.now()};ps.setPointerCapture?.(e.pointerId)});ps.addEventListener('pointerup',e=>{if(!settings.touchGestures||!state.pointerStart||e.target.closest('button'))return;const dx=e.clientX-state.pointerStart.x,dy=e.clientY-state.pointerStart.y,dt=performance.now()-state.pointerStart.t;state.pointerStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<32&&dt<550)perform('playPause');else if(Math.abs(dx)>Math.abs(dy))perform(dx>0?'nextMark':'prevMark');else perform(dy<0?'faster':'slower')});ps.addEventListener('wheel',e=>{e.preventDefault();if(e.shiftKey)changePace(e.deltaY<0?1:-1);else{state.scrollY=clamp(state.scrollY+e.deltaY*.65,0,state.maxY);updateTransform();updateHud()}},{passive:false});
}

function init(){loadSettings();loadDraft();syncControls();renderLibrary();renderKeyMappings();renderGamepadActions();setupBindings();requestAnimationFrame(pollGamepads);scriptStats();applyPromptAppearance();setInterval(()=>{if(document.activeElement!==$('scriptInput'))$('autosaveBadge').textContent='Auto-save ready'},5000)}
init();
